[package]
name = "microwave-efficiency"
version = "1.0.0"
authors = ["HiraokaTakuya <hiraoka@heroz.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "*"
